### ISSUE TITLE
Feature request: Add option for giving AI starting farms

### ISSUE THREAD

**Issue by MichaelS11** [yiotro/Antiyoy#77]
Was thinking an easy way to make the AI a little more difficult would be to have a slider to give the AI starting farms. Maybe the slider would go from 0 to 10.

So for example if you selected 2, each AI color would start with two hexs that had farms build.

**Comment by yiotro** [comment]
Well, that would be unfair and also I think that good players will still be winning easily. 

Also, it can be already done in level editor.

**Comment by MichaelS11** [comment]
Forgot to mention the request was for Skirmish mode.

I think for most players it would make it more challenging to play Skirmish mode without having to spend a lot of timing adjusting the AI. Plus people can adjust it to the level they want. The default would be 0, exactly what it is now.

**Comment by yiotro** [comment]
Yes, I understand that it's for skirmish. And it won't be hard to do.

But I want to keep UI simple and clean, so I only add things that make very noticeable difference. In case of farms I think that it won't make game more interesting to play. The only thing that can do that is better AI, but it's really hard to make.

**Comment by MichaelS11** [comment]
Sure, better AI would be ideal but I think farms would make a noticeable difference. I and I think others are not necessarily looking for a super hard challenge. Just something to make a Skirmish versus the AI a little more difficult, a little more challenging.

In the harder custom user maps many of them give the AI farms to make the map more challenging.

**Comment by OvermindDL1** [comment]
Maybe make a Handicap slider or so, can do things like give free starting farms, maybe an income multiplier or something.  Nice and generic and simple and easily changed in the future.

**Comment by Maaartinus** [comment]
I'd strongly prefer an income multiplier to an initial advantage. Some funny boost in the middle game would be even better. Skirmish is fun, but once I get up and running, it's just a matter of time... and at that moment I'd enjoy a boost for the AI players.

**Comment by yiotro** [comment]
Have you tried 'Slay rules'? In my opinion, game is much more interesting and challenging with them. Even more, game was initially designed for those rules.

**Comment by MichaelS11** [comment]
Yes, finished everything but about a dozen user maps. I like both slay & non-slay. I personaly enjoy non-slay a little more, what I usually play skirmish mode in.

Being able to give the AI some kind of advantage would be nice and putting under more options would still keep the UI clean.

**Comment by MichaelS11** [comment]
So are there any options that you would do for a simple improvement of the AI?

**Comment by yiotro** [comment]
There is no easy way to improve AI. The only way is to make new version from scratch, with much more complicated principles implemented. But it's very hard to do and will take a lot of time.

**Comment by MichaelS11** [comment]
Right, was saying like give them more money, more farms, or what ever way you think is best.

**Comment by Maaartinus** [comment]
There are some trivial blunders the AI ofyen does:

- building the stronger towers where he strongest piece attacks - just wasting resources
- never upgrading the second strongest piece

**Comment by MichaelS11** [comment]
@yiotro So what do you think?

**Comment by yiotro** [comment]
AI's biggest problem is inability to properly attack. AI just randomly attacks things that are easy to attack, without any tactic or strategy. Of course, with more money AI will do more stuff, but most of that money will be spent for nothing.

**Comment by costin88boss** [comment]
@yiotro I think the best way to make ai difficult is to make him extremely defensive when he is near enemy, make him capture farms fastest possible making only people and ignoring any other enemy until he is big enough getting to 20+ money he will start making houses and if enemy is 3 farms away from him he will upgrade his own people to soldiers. If able and enemy is stronger, red soldier, and keep economy of money for towers. After enemy comes near him the ai will try to defend with towers, If he detects red soldiers from enemy or enemy is defending himself or enemy destroys a tower then ai will try trapping the enemy red soldiers to make them die of money, or if enemy is defending himself then ai will continue growing and getting farms until no any available farm, he will start going to battle and if he detects red soldier near better towers the ai will try to defend himself until he detects a 3x3 spot which is human, soldier, or tower, and he will go there while enemy may go pass capture his farms the ai will make a trap until his soldiers dies and will continue attacking. 

I suggest making ais defend if red soldiers, attack if soldiers or humans, and trap if red soldiers or towers but a little spot where it's just soldiers human or tower.

Dont report me for cancer long message, I make big and detailed and many ideas if I I got ideas.  See also my post with some ideas, I got cancer there too.

Edit: I think you should add the tactics i showed you. Trap, low defend spot, high defend, high farms growth and money economy (keeping for later) tactics. And maybe add a difficulty player-like  which ai will use player's  tactics and strategy. For sure ais are better than players, because they calculates fast and detects, so maybe you can make ais follow player tactics In a difficulty called player-like.

**Comment by yiotro** [comment]
> I think the best way to make ai difficult is to make him extremely defensive when he is near enemy

It's already like that.

> make him capture farms fastest possible 

I'm not sure about it, but I think that AI already prioritizes farms over other hexes.

**Comment by costin88boss** [comment]
@yiotro  then maybe, I know it is a bit hard, if not, hard to make at least some common strategies and tactics. also you forgot to list your new game on other games list from tutorial panel. just saying you forgot.
